# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuando', models.CharField(max_length=128)),
                ('donde', models.CharField(max_length=128)),
                ('como', models.CharField(max_length=128)),
                ('que', models.CharField(max_length=128)),
                ('texto', models.CharField(max_length=140)),
                ('fecha', models.DateTimeField()),
            ],
        ),
    ]
